### PR TITLE
Team5 - sprint 1 - UI

### PR DESCRIPTION
**Pull request by usrnatc**
### Dialogue box
 - Actor object used to display dialogue in-game

### Main menu
 - display image fullscreen
 - play game functionality
 - settings menu functionality
 - exit game functionality

### Pause menu
 - pause game time functionality
 - settings menu functionality
 - resume game functionality
 - exit game functionality

### In-game UI
 - display resource count
 - display minimap
 - display player current health
 - container for dialogue boxes

[wiki documentation](https://github.com/UQdeco2800/2022-studio-3/wiki/UI)

### CODE REVIEW

**Comment by usrnatc** [comment]
Dialogue boxes are planned to be wholly mutable, currently not everything is for compatibilities and designs sake.
No dialogue box is currently being displayed in game, as cutscenes have not been fully implemented yet.

**Comment by Suuoooooooo** [comment]
Pause Menu is planned to be toggled using ESC key instead of a button on the top right of the in-game screen, and there are still some minor issues between pause menu and camera that yet to be fixed

**Comment by yobicakes** [comment]
The game engine displays a main menu with a background image and basic sound. The user may choose to "Start Game" which  initialises game play. In the future, we plant to implement a cut scene that acts as a "transition" between the initial menu and game play. In the future, we also plan to replace the "Text Buttons" with "Image Buttons" using the Image button designs.

**Comment by alyshaziya** [comment]
The main game screen contains an updatable widget containing the current count of player resources in the top right corner. The resource tracking events need to be added to the display file to link the UI with resource tracking functionality.

**Pull request merged**
